disjunction {
  disjuncts {
    dual_until {
      front {
        atomic { symbol: "enter" }
      }
      back {
        negation {
          formula {
            disjunction {
              disjuncts {
                atomic { symbol: "finish_close" }
              }
              disjuncts {
                finally {
                  formula { atomic { symbol: "finish_close" } }
                  interval {
                    lower {
                      value: 0
                      bound_type: WEAK
                    }
                    upper {
                      value: 1
                      bound_type: WEAK
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  disjuncts {
    dual_until {
      front {
        atomic { symbol: "start_open" }
      }
      back {
        negation {
         formula { atomic { symbol: "leave" } }
        }
      }
    }
  }
  disjuncts {
    dual_until {
      front {
        atomic { symbol: "travel" }
      }
      back {
        negation {
         formula { atomic { symbol: "finish_open" } }
        }
      }
    }
  }
}
