disjunction {
  disjuncts {
    dual_until {
      front {
        disjunction {
          disjuncts {
            atomic { symbol: "enter" }
          }
          disjuncts {
            finally {
              formula { atomic { symbol: "enter" } }
              interval {
                lower {
                  value: 0
                  bound_type: WEAK
                }
                upper {
                  value: 1
                  bound_type: WEAK
                }
              }
            }
          }
        }
      }
      back {
        negation {
          formula {
            atomic { symbol: "finish_close" }
          }
        }
      }
    }
  }
  disjuncts {
    dual_until {
      front {
        atomic { symbol: "start_open" }
      }
      back {
        negation {
         formula { atomic { symbol: "leave" } }
        }
      }
    }
  }
  disjuncts {
    dual_until {
      front {
        atomic { symbol: "travel" }
      }
      back {
        negation {
         formula { atomic { symbol: "finish_open" } }
        }
      }
    }
  }
}
